export type { table } from './aliases';
export { default as isBoolean } from './isBoolean';
export { default as isDate } from './isDate';
export { default as isFunction } from './isFunction';
export { default as isNumber } from './isNumber';
export { default as isObject } from './isObject';
export { default as isRegExp } from './isRegExp';
export { default as isString } from './isString';
export { default as isTable } from './isTable';
export { default as toType } from './toType';
